# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: addVideo.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='addVideo.proto',
  package='protofile.addVideo',
  serialized_pb=_b('\n\x0e\x61\x64\x64Video.proto\x12\x12protofile.addVideo\"R\n\x0f\x61\x64\x64VideoRequest\x12\x0f\n\x07videoId\x18\x01 \x02(\t\x12\x10\n\x08gameType\x18\x02 \x02(\t\x12\x0f\n\x07\x62\x65tTime\x18\x03 \x02(\x05\x12\x0b\n\x03url\x18\x04 \x02(\t\" \n\x10\x61\x64\x64VideoResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_ADDVIDEOREQUEST = _descriptor.Descriptor(
  name='addVideoRequest',
  full_name='protofile.addVideo.addVideoRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videoId', full_name='protofile.addVideo.addVideoRequest.videoId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameType', full_name='protofile.addVideo.addVideoRequest.gameType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='betTime', full_name='protofile.addVideo.addVideoRequest.betTime', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='protofile.addVideo.addVideoRequest.url', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=120,
)


_ADDVIDEORESPONSE = _descriptor.Descriptor(
  name='addVideoResponse',
  full_name='protofile.addVideo.addVideoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protofile.addVideo.addVideoResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=122,
  serialized_end=154,
)

DESCRIPTOR.message_types_by_name['addVideoRequest'] = _ADDVIDEOREQUEST
DESCRIPTOR.message_types_by_name['addVideoResponse'] = _ADDVIDEORESPONSE

addVideoRequest = _reflection.GeneratedProtocolMessageType('addVideoRequest', (_message.Message,), dict(
  DESCRIPTOR = _ADDVIDEOREQUEST,
  __module__ = 'addVideo_pb2'
  # @@protoc_insertion_point(class_scope:protofile.addVideo.addVideoRequest)
  ))
_sym_db.RegisterMessage(addVideoRequest)

addVideoResponse = _reflection.GeneratedProtocolMessageType('addVideoResponse', (_message.Message,), dict(
  DESCRIPTOR = _ADDVIDEORESPONSE,
  __module__ = 'addVideo_pb2'
  # @@protoc_insertion_point(class_scope:protofile.addVideo.addVideoResponse)
  ))
_sym_db.RegisterMessage(addVideoResponse)


# @@protoc_insertion_point(module_scope)
