# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: bulletin.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='bulletin.proto',
  package='protofile.bulletin',
  serialized_pb=_b('\n\x0e\x62ulletin.proto\x12\x12protofile.bulletin\"D\n\x10\x62ulletinResponse\x12\x11\n\tbeginTime\x18\x01 \x02(\t\x12\x0f\n\x07\x65ndTime\x18\x02 \x02(\t\x12\x0c\n\x04text\x18\x03 \x02(\t')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_BULLETINRESPONSE = _descriptor.Descriptor(
  name='bulletinResponse',
  full_name='protofile.bulletin.bulletinResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='beginTime', full_name='protofile.bulletin.bulletinResponse.beginTime', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='endTime', full_name='protofile.bulletin.bulletinResponse.endTime', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='text', full_name='protofile.bulletin.bulletinResponse.text', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=38,
  serialized_end=106,
)

DESCRIPTOR.message_types_by_name['bulletinResponse'] = _BULLETINRESPONSE

bulletinResponse = _reflection.GeneratedProtocolMessageType('bulletinResponse', (_message.Message,), dict(
  DESCRIPTOR = _BULLETINRESPONSE,
  __module__ = 'bulletin_pb2'
  # @@protoc_insertion_point(class_scope:protofile.bulletin.bulletinResponse)
  ))
_sym_db.RegisterMessage(bulletinResponse)


# @@protoc_insertion_point(module_scope)
