# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: getVideos.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='getVideos.proto',
  package='protofile.video.getVideos',
  serialized_pb=_b('\n\x0fgetVideos.proto\x12\x19protoFile.video.getVideos\"!\n\x10getVideosRequest\x12\r\n\x05query\x18\x01 \x01(\t\"\\\n\x11getVideosResponse\x12\x12\n\nvideoCount\x18\x01 \x02(\x05\x12\x33\n\x05video\x18\x02 \x03(\x0b\x32$.protofile.video.getVideos.VideoInfo\"\x95\x01\n\tVideoInfo\x12\x0f\n\x07videoId\x18\x01 \x02(\t\x12\x10\n\x08gameType\x18\x02 \x02(\t\x12\x0f\n\x07\x62\x65tTime\x18\x03 \x02(\t\x12\x0b\n\x03url\x18\x04 \x02(\t\x12\x12\n\ntableCount\x18\x05 \x02(\x05\x12\x33\n\x05table\x18\x06 \x03(\x0b\x32$.protofile.video.getVideos.TableInfo\"<\n\tTableInfo\x12\x0f\n\x07tableId\x18\x01 \x02(\t\x12\x0f\n\x07limitId\x18\x02 \x02(\x05\x12\r\n\x05seats\x18\x03 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_GETVIDEOSREQUEST = _descriptor.Descriptor(
  name='getVideosRequest',
  full_name='protofile.video.getVideos.getVideosRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='query', full_name='protofile.video.getVideos.getVideosRequest.query', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=79,
)


_GETVIDEOSRESPONSE = _descriptor.Descriptor(
  name='getVideosResponse',
  full_name='protofile.video.getVideos.getVideosResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videoCount', full_name='protofile.video.getVideos.getVideosResponse.videoCount', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='video', full_name='protofile.video.getVideos.getVideosResponse.video', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=173,
)


_VIDEOINFO = _descriptor.Descriptor(
  name='VideoInfo',
  full_name='protofile.video.getVideos.VideoInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='videoId', full_name='protofile.video.getVideos.VideoInfo.videoId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='gameType', full_name='protofile.video.getVideos.VideoInfo.gameType', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='betTime', full_name='protofile.video.getVideos.VideoInfo.betTime', index=2,
      number=3, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='url', full_name='protofile.video.getVideos.VideoInfo.url', index=3,
      number=4, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tableCount', full_name='protofile.video.getVideos.VideoInfo.tableCount', index=4,
      number=5, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='table', full_name='protofile.video.getVideos.VideoInfo.table', index=5,
      number=6, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=176,
  serialized_end=325,
)


_TABLEINFO = _descriptor.Descriptor(
  name='TableInfo',
  full_name='protofile.video.getVideos.TableInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='tableId', full_name='protofile.video.getVideos.TableInfo.tableId', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='limitId', full_name='protofile.video.getVideos.TableInfo.limitId', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='seats', full_name='protofile.video.getVideos.TableInfo.seats', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=327,
  serialized_end=387,
)

_GETVIDEOSRESPONSE.fields_by_name['video'].message_type = _VIDEOINFO
_VIDEOINFO.fields_by_name['table'].message_type = _TABLEINFO
DESCRIPTOR.message_types_by_name['getVideosRequest'] = _GETVIDEOSREQUEST
DESCRIPTOR.message_types_by_name['getVideosResponse'] = _GETVIDEOSRESPONSE
DESCRIPTOR.message_types_by_name['VideoInfo'] = _VIDEOINFO
DESCRIPTOR.message_types_by_name['TableInfo'] = _TABLEINFO

getVideosRequest = _reflection.GeneratedProtocolMessageType('getVideosRequest', (_message.Message,), dict(
  DESCRIPTOR = _GETVIDEOSREQUEST,
  __module__ = 'getVideos_pb2'
  # @@protoc_insertion_point(class_scope:protofile.video.getVideos.getVideosRequest)
  ))
_sym_db.RegisterMessage(getVideosRequest)

getVideosResponse = _reflection.GeneratedProtocolMessageType('getVideosResponse', (_message.Message,), dict(
  DESCRIPTOR = _GETVIDEOSRESPONSE,
  __module__ = 'getVideos_pb2'
  # @@protoc_insertion_point(class_scope:protofile.video.getVideos.getVideosResponse)
  ))
_sym_db.RegisterMessage(getVideosResponse)

VideoInfo = _reflection.GeneratedProtocolMessageType('VideoInfo', (_message.Message,), dict(
  DESCRIPTOR = _VIDEOINFO,
  __module__ = 'getVideos_pb2'
  # @@protoc_insertion_point(class_scope:protofile.video.getVideos.VideoInfo)
  ))
_sym_db.RegisterMessage(VideoInfo)

TableInfo = _reflection.GeneratedProtocolMessageType('TableInfo', (_message.Message,), dict(
  DESCRIPTOR = _TABLEINFO,
  __module__ = 'getVideos_pb2'
  # @@protoc_insertion_point(class_scope:protofile.video.getVideos.TableInfo)
  ))
_sym_db.RegisterMessage(TableInfo)


# @@protoc_insertion_point(module_scope)
