# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: login.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='login.proto',
  package='protofile.login',
  serialized_pb=_b('\n\x0blogin.proto\x12\x0fprotofile.login\"3\n\x0cloginRequest\x12\x11\n\tloginname\x18\x01 \x02(\t\x12\x10\n\x08password\x18\x02 \x02(\t\"@\n\x13loginResultResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05\x12\r\n\x05token\x18\x02 \x01(\t\x12\x0c\n\x04\x66lag\x18\x03 \x02(\x05\"4\n\x10userInfoResponse\x12\x10\n\x08nickname\x18\x01 \x02(\t\x12\x0e\n\x06\x63redit\x18\x02 \x02(\x02\"4\n\x10loginGameRequest\x12\x11\n\tloginname\x18\x01 \x02(\t\x12\r\n\x05token\x18\x02 \x02(\t\"\'\n\x17loginGameResultResponse\x12\x0c\n\x04\x63ode\x18\x01 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_LOGINREQUEST = _descriptor.Descriptor(
  name='loginRequest',
  full_name='protofile.login.loginRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginname', full_name='protofile.login.loginRequest.loginname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='password', full_name='protofile.login.loginRequest.password', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=83,
)


_LOGINRESULTRESPONSE = _descriptor.Descriptor(
  name='loginResultResponse',
  full_name='protofile.login.loginResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protofile.login.loginResultResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='protofile.login.loginResultResponse.token', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='flag', full_name='protofile.login.loginResultResponse.flag', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=85,
  serialized_end=149,
)


_USERINFORESPONSE = _descriptor.Descriptor(
  name='userInfoResponse',
  full_name='protofile.login.userInfoResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='nickname', full_name='protofile.login.userInfoResponse.nickname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='credit', full_name='protofile.login.userInfoResponse.credit', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=151,
  serialized_end=203,
)


_LOGINGAMEREQUEST = _descriptor.Descriptor(
  name='loginGameRequest',
  full_name='protofile.login.loginGameRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='loginname', full_name='protofile.login.loginGameRequest.loginname', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='token', full_name='protofile.login.loginGameRequest.token', index=1,
      number=2, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=205,
  serialized_end=257,
)


_LOGINGAMERESULTRESPONSE = _descriptor.Descriptor(
  name='loginGameResultResponse',
  full_name='protofile.login.loginGameResultResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='code', full_name='protofile.login.loginGameResultResponse.code', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=259,
  serialized_end=298,
)

DESCRIPTOR.message_types_by_name['loginRequest'] = _LOGINREQUEST
DESCRIPTOR.message_types_by_name['loginResultResponse'] = _LOGINRESULTRESPONSE
DESCRIPTOR.message_types_by_name['userInfoResponse'] = _USERINFORESPONSE
DESCRIPTOR.message_types_by_name['loginGameRequest'] = _LOGINGAMEREQUEST
DESCRIPTOR.message_types_by_name['loginGameResultResponse'] = _LOGINGAMERESULTRESPONSE

loginRequest = _reflection.GeneratedProtocolMessageType('loginRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINREQUEST,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:protofile.login.loginRequest)
  ))
_sym_db.RegisterMessage(loginRequest)

loginResultResponse = _reflection.GeneratedProtocolMessageType('loginResultResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINRESULTRESPONSE,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:protofile.login.loginResultResponse)
  ))
_sym_db.RegisterMessage(loginResultResponse)

userInfoResponse = _reflection.GeneratedProtocolMessageType('userInfoResponse', (_message.Message,), dict(
  DESCRIPTOR = _USERINFORESPONSE,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:protofile.login.userInfoResponse)
  ))
_sym_db.RegisterMessage(userInfoResponse)

loginGameRequest = _reflection.GeneratedProtocolMessageType('loginGameRequest', (_message.Message,), dict(
  DESCRIPTOR = _LOGINGAMEREQUEST,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:protofile.login.loginGameRequest)
  ))
_sym_db.RegisterMessage(loginGameRequest)

loginGameResultResponse = _reflection.GeneratedProtocolMessageType('loginGameResultResponse', (_message.Message,), dict(
  DESCRIPTOR = _LOGINGAMERESULTRESPONSE,
  __module__ = 'login_pb2'
  # @@protoc_insertion_point(class_scope:protofile.login.loginGameResultResponse)
  ))
_sym_db.RegisterMessage(loginGameResultResponse)


# @@protoc_insertion_point(module_scope)
