# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: personalLimit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='personalLimit.proto',
  package='protofile.personalLimit',
  serialized_pb=_b('\n\x13personalLimit.proto\x12\x17protofile.personalLimit\"f\n\x15personalLimitResponse\x12\x0e\n\x06number\x18\x01 \x02(\x05\x12=\n\rpersonalLimit\x18\x02 \x03(\x0b\x32&.protofile.personalLimit.personalLimit\"R\n\rpersonalLimit\x12\x0f\n\x07limitid\x18\x01 \x02(\t\x12\x10\n\x08playtype\x18\x02 \x02(\x05\x12\x0e\n\x06minval\x18\x03 \x02(\x05\x12\x0e\n\x06maxval\x18\x04 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_PERSONALLIMITRESPONSE = _descriptor.Descriptor(
  name='personalLimitResponse',
  full_name='protofile.personalLimit.personalLimitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='protofile.personalLimit.personalLimitResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='personalLimit', full_name='protofile.personalLimit.personalLimitResponse.personalLimit', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=48,
  serialized_end=150,
)


_PERSONALLIMIT = _descriptor.Descriptor(
  name='personalLimit',
  full_name='protofile.personalLimit.personalLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limitid', full_name='protofile.personalLimit.personalLimit.limitid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playtype', full_name='protofile.personalLimit.personalLimit.playtype', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minval', full_name='protofile.personalLimit.personalLimit.minval', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxval', full_name='protofile.personalLimit.personalLimit.maxval', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=152,
  serialized_end=234,
)

_PERSONALLIMITRESPONSE.fields_by_name['personalLimit'].message_type = _PERSONALLIMIT
DESCRIPTOR.message_types_by_name['personalLimitResponse'] = _PERSONALLIMITRESPONSE
DESCRIPTOR.message_types_by_name['personalLimit'] = _PERSONALLIMIT

personalLimitResponse = _reflection.GeneratedProtocolMessageType('personalLimitResponse', (_message.Message,), dict(
  DESCRIPTOR = _PERSONALLIMITRESPONSE,
  __module__ = 'personalLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.personalLimit.personalLimitResponse)
  ))
_sym_db.RegisterMessage(personalLimitResponse)

personalLimit = _reflection.GeneratedProtocolMessageType('personalLimit', (_message.Message,), dict(
  DESCRIPTOR = _PERSONALLIMIT,
  __module__ = 'personalLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.personalLimit.personalLimit)
  ))
_sym_db.RegisterMessage(personalLimit)


# @@protoc_insertion_point(module_scope)
