# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tableLimit.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tableLimit.proto',
  package='protofile.tableLimit',
  serialized_pb=_b('\n\x10tableLimit.proto\x12\x14protofile.tableLimit\"Z\n\x12tableLimitResponse\x12\x0e\n\x06number\x18\x01 \x02(\x05\x12\x34\n\ntableLimit\x18\x02 \x03(\x0b\x32 .protofile.tableLimit.tableLimit\"O\n\ntableLimit\x12\x0f\n\x07limitid\x18\x01 \x02(\t\x12\x10\n\x08playtype\x18\x02 \x02(\x05\x12\x0e\n\x06minval\x18\x03 \x02(\x05\x12\x0e\n\x06maxval\x18\x04 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_TABLELIMITRESPONSE = _descriptor.Descriptor(
  name='tableLimitResponse',
  full_name='protofile.tableLimit.tableLimitResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='number', full_name='protofile.tableLimit.tableLimitResponse.number', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='tableLimit', full_name='protofile.tableLimit.tableLimitResponse.tableLimit', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=132,
)


_TABLELIMIT = _descriptor.Descriptor(
  name='tableLimit',
  full_name='protofile.tableLimit.tableLimit',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='limitid', full_name='protofile.tableLimit.tableLimit.limitid', index=0,
      number=1, type=9, cpp_type=9, label=2,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='playtype', full_name='protofile.tableLimit.tableLimit.playtype', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='minval', full_name='protofile.tableLimit.tableLimit.minval', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='maxval', full_name='protofile.tableLimit.tableLimit.maxval', index=3,
      number=4, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=134,
  serialized_end=213,
)

_TABLELIMITRESPONSE.fields_by_name['tableLimit'].message_type = _TABLELIMIT
DESCRIPTOR.message_types_by_name['tableLimitResponse'] = _TABLELIMITRESPONSE
DESCRIPTOR.message_types_by_name['tableLimit'] = _TABLELIMIT

tableLimitResponse = _reflection.GeneratedProtocolMessageType('tableLimitResponse', (_message.Message,), dict(
  DESCRIPTOR = _TABLELIMITRESPONSE,
  __module__ = 'tableLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.tableLimit.tableLimitResponse)
  ))
_sym_db.RegisterMessage(tableLimitResponse)

tableLimit = _reflection.GeneratedProtocolMessageType('tableLimit', (_message.Message,), dict(
  DESCRIPTOR = _TABLELIMIT,
  __module__ = 'tableLimit_pb2'
  # @@protoc_insertion_point(class_scope:protofile.tableLimit.tableLimit)
  ))
_sym_db.RegisterMessage(tableLimit)


# @@protoc_insertion_point(module_scope)
